package VentanaJava;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pzamoram
 */
public class ModificarContrasena extends javax.swing.JFrame {

    /**
     * Creates new form ModificarContrasena
     */
    public ModificarContrasena() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ModificarContrasenaTitulo = new javax.swing.JLabel();
        ContrasenaActualTitulo = new javax.swing.JLabel();
        ContrasenaActualIngresar = new javax.swing.JPasswordField();
        ContrasenaNuevaTitulo = new javax.swing.JLabel();
        ContrasenaNuevaIngresar = new javax.swing.JPasswordField();
        ConfirmarContrasenaTitulo = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        GuardarDatos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ModificarContrasenaTitulo.setFont(new java.awt.Font("Cambria", 0, 22)); // NOI18N
        ModificarContrasenaTitulo.setText("Modificar Contraseña");

        ContrasenaActualTitulo.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        ContrasenaActualTitulo.setText("Contraseña Actual");

        ContrasenaActualIngresar.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        ContrasenaActualIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContrasenaActualIngresarActionPerformed(evt);
            }
        });

        ContrasenaNuevaTitulo.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        ContrasenaNuevaTitulo.setText("Nueva Contraseña");

        ContrasenaNuevaIngresar.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        ContrasenaNuevaIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContrasenaNuevaIngresarActionPerformed(evt);
            }
        });

        ConfirmarContrasenaTitulo.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        ConfirmarContrasenaTitulo.setText("Confirmar Contraseña");

        jPasswordField1.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N

        GuardarDatos.setFont(new java.awt.Font("Calibri Light", 0, 22)); // NOI18N
        GuardarDatos.setText("Guardar Datos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ContrasenaActualTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ContrasenaNuevaTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(ConfirmarContrasenaTitulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(GuardarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ContrasenaActualIngresar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ContrasenaNuevaIngresar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(ModificarContrasenaTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ModificarContrasenaTitulo)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContrasenaActualTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ContrasenaActualIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContrasenaNuevaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ContrasenaNuevaIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmarContrasenaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(GuardarDatos)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ContrasenaActualIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContrasenaActualIngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContrasenaActualIngresarActionPerformed

    private void ContrasenaNuevaIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContrasenaNuevaIngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContrasenaNuevaIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarContrasena().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ConfirmarContrasenaTitulo;
    private javax.swing.JPasswordField ContrasenaActualIngresar;
    private javax.swing.JLabel ContrasenaActualTitulo;
    private javax.swing.JPasswordField ContrasenaNuevaIngresar;
    private javax.swing.JLabel ContrasenaNuevaTitulo;
    private javax.swing.JButton GuardarDatos;
    private javax.swing.JLabel ModificarContrasenaTitulo;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
