/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VentanaJava;

/**
 *
 * @author lopez.p.2
 */
public class PlanificacionEngorde extends javax.swing.JFrame {
    
    /**
     * Creates new form PlanificacionEngorde
     */
    public PlanificacionEngorde() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PlanificacionCosechaMedianoPlazo = new javax.swing.JButton();
        PlanificacionCosechaCortoPlazo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        PlanificacionIngresoMedianoPlazo = new javax.swing.JButton();
        PlanificacionIngresoCortoPlazo = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenu15 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();
        jMenu17 = new javax.swing.JMenu();
        jMenu18 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PlanificacionCosechaMedianoPlazo.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        PlanificacionCosechaMedianoPlazo.setText("Planificación Cosecha Mediano Plazo");

        PlanificacionCosechaCortoPlazo.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        PlanificacionCosechaCortoPlazo.setText("Planificación Cosecha Corto Plazo");

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 22)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Planificación de Engorde");

        PlanificacionIngresoMedianoPlazo.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        PlanificacionIngresoMedianoPlazo.setText("Planificación Ingreso Mediano Plazo");

        PlanificacionIngresoCortoPlazo.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        PlanificacionIngresoCortoPlazo.setText("Planificación Ingreso Corto Plazo");

        jMenuBar2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jMenu5.setText("Gestionar Datos");
        jMenu5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jMenu8.setText("Planta de Procesamiento");
        jMenu8.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jMenu5.add(jMenu8);

        jMenu6.setText("Procesos de Engorde");
        jMenu6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jMenu5.add(jMenu6);

        jMenu9.setText("Secuencia de Transporte");
        jMenu9.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jMenu5.add(jMenu9);

        jMenu10.setText("Galeras");
        jMenu10.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jMenu5.add(jMenu10);

        jMenu15.setText("Límites de Rangos de Peso");
        jMenu15.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jMenu5.add(jMenu15);

        jMenuBar2.add(jMenu5);

        jMenu16.setText("Importar Datos");
        jMenu16.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jMenu17.setText("Proyección de Demanda");
        jMenu17.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jMenu16.add(jMenu17);

        jMenu18.setText("Datos Históricos de Mortalidad");
        jMenu18.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jMenu16.add(jMenu18);

        jMenuBar2.add(jMenu16);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PlanificacionIngresoMedianoPlazo, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                    .addComponent(PlanificacionIngresoCortoPlazo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PlanificacionCosechaMedianoPlazo)
                    .addComponent(PlanificacionCosechaCortoPlazo, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlanificacionIngresoMedianoPlazo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PlanificacionCosechaMedianoPlazo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlanificacionIngresoCortoPlazo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PlanificacionCosechaCortoPlazo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlanificacionEngorde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlanificacionEngorde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlanificacionEngorde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlanificacionEngorde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlanificacionEngorde().setVisible(true);
                            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PlanificacionCosechaCortoPlazo;
    private javax.swing.JButton PlanificacionCosechaMedianoPlazo;
    private javax.swing.JButton PlanificacionIngresoCortoPlazo;
    private javax.swing.JButton PlanificacionIngresoMedianoPlazo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar2;
    // End of variables declaration//GEN-END:variables
}
