package VentanaJava;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pzamoram
 */
public class PrincipalPlanificacion extends javax.swing.JFrame {
    int usuarioAutenticado;
    /**
     * Creates new form PrincipalPlanificacion
     */
    public PrincipalPlanificacion(int idUsuario) {
        initComponents();
        usuarioAutenticado=idUsuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jButton3 = new javax.swing.JButton();
        jDialog1 = new javax.swing.JDialog();
        AdministracionUsuarios = new javax.swing.JButton();
        PlanificacionEngorde = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        Configuracion = new javax.swing.JMenu();
        ModificarUsuario = new javax.swing.JMenuItem();
        CambiarContrasena = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu3.setText("jMenu3");

        jButton3.setText("jButton3");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AdministracionUsuarios.setFont(new java.awt.Font("Cambria", 0, 22)); // NOI18N
        AdministracionUsuarios.setText("Administración de Usuarios");
        AdministracionUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdministracionUsuariosActionPerformed(evt);
            }
        });

        PlanificacionEngorde.setFont(new java.awt.Font("Cambria", 0, 22)); // NOI18N
        PlanificacionEngorde.setText("Planificación de Engorde");
        PlanificacionEngorde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlanificacionEngordeActionPerformed(evt);
            }
        });

        Configuracion.setText("Configuración");
        Configuracion.setFont(new java.awt.Font("Calibri Light", 0, 22)); // NOI18N

        ModificarUsuario.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        ModificarUsuario.setText("Modificar Nombre de Usuario");
        ModificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarUsuarioActionPerformed(evt);
            }
        });
        Configuracion.add(ModificarUsuario);

        CambiarContrasena.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        CambiarContrasena.setText("Modificar Contraseña");
        CambiarContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambiarContrasenaActionPerformed(evt);
            }
        });
        Configuracion.add(CambiarContrasena);

        jMenuBar2.add(Configuracion);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(AdministracionUsuarios)
                .addGap(98, 98, 98)
                .addComponent(PlanificacionEngorde, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdministracionUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PlanificacionEngorde, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdministracionUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdministracionUsuariosActionPerformed
        AdministracionUsuarios abrir = new AdministracionUsuarios();
        abrir.setVisible(true);
    }//GEN-LAST:event_AdministracionUsuariosActionPerformed

    private void PlanificacionEngordeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlanificacionEngordeActionPerformed
        mostrarplanificacionengorde();
    }//GEN-LAST:event_PlanificacionEngordeActionPerformed

    private void CambiarContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambiarContrasenaActionPerformed
        ModificarContrasena abrir = new ModificarContrasena();
        abrir.setVisible(true);
    }//GEN-LAST:event_CambiarContrasenaActionPerformed

    private void ModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarUsuarioActionPerformed
        int a=0;
        ModificarUsuario1 abrir = new ModificarUsuario1(a);
        abrir.setVisible(true);
    }//GEN-LAST:event_ModificarUsuarioActionPerformed
    public void mostrarplanificacionengorde() {
        PlanificacionEngorde lol=new PlanificacionEngorde();
        lol.setVisible(true);
        lol.setLocationRelativeTo(this);
  }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalPlanificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalPlanificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalPlanificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalPlanificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                int a=0;
                new PrincipalPlanificacion(a).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdministracionUsuarios;
    private javax.swing.JMenuItem CambiarContrasena;
    private javax.swing.JMenu Configuracion;
    private javax.swing.JMenuItem ModificarUsuario;
    private javax.swing.JButton PlanificacionEngorde;
    private javax.swing.JButton jButton3;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
