/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VentanaJava;

import static VentanaJava.Galeras.TablaGaleras;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lopez.p.2
 */
public class ProcesosEngorde extends javax.swing.JFrame {

    /**
     * Creates new form ProcesosEngorde
     */
    public ProcesosEngorde() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        RegistrarNuevoIngreso = new javax.swing.JButton();
        ModificarDatosIngreso = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        TablaIngreso = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaPesaje = new javax.swing.JTable();
        RegistrarNuevoPesaje = new javax.swing.JButton();
        ModificarDatosPesaje = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        TablaMortalidad = new javax.swing.JTable();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        RegistrarNuevasModalidades = new javax.swing.JButton();
        ModificarDatosMortalidades = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N

        jPanel2.setToolTipText("Filtro");
        jPanel2.setName(""); // NOI18N

        RegistrarNuevoIngreso.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        RegistrarNuevoIngreso.setText("Registrar Nuevo Ingreso");
        RegistrarNuevoIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarNuevoIngresoActionPerformed(evt);
            }
        });

        ModificarDatosIngreso.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        ModificarDatosIngreso.setText("Modificar Datos de Ingreso");

        jScrollPane5.setViewportView(jTextPane1);

        TablaIngreso.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        TablaIngreso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No. Galera", "Fecha de Ingreso", "Cantidad de Aves", "Edad de Reproductora", "id Ingresos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablaIngreso.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TablaIngresoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane11.setViewportView(TablaIngreso);

        jScrollPane10.setViewportView(jScrollPane11);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(RegistrarNuevoIngreso)
                        .addGap(18, 18, 18)
                        .addComponent(ModificarDatosIngreso)))
                .addContainerGap(263, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistrarNuevoIngreso)
                    .addComponent(ModificarDatosIngreso))
                .addGap(32, 32, 32))
        );

        jTabbedPane1.addTab("Ingreso", jPanel2);

        TablaPesaje.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        TablaPesaje.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No. Galera", "Fecha de Pesaje", "Peso Promedio", "Desviación Estándar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Short.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablaPesaje.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TablaPesajeAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane4.setViewportView(TablaPesaje);

        jScrollPane3.setViewportView(jScrollPane4);

        RegistrarNuevoPesaje.setFont(new java.awt.Font("Calibri Light", 0, 22)); // NOI18N
        RegistrarNuevoPesaje.setText("Registrar Nuevo Pesaje");
        RegistrarNuevoPesaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarNuevoPesajeActionPerformed(evt);
            }
        });

        ModificarDatosPesaje.setFont(new java.awt.Font("Calibri Light", 0, 22)); // NOI18N
        ModificarDatosPesaje.setText("Modificar Datos de Pesaje");

        jScrollPane6.setViewportView(jTextPane2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 915, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RegistrarNuevoPesaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ModificarDatosPesaje)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistrarNuevoPesaje)
                    .addComponent(ModificarDatosPesaje))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Pesaje", jPanel3);

        TablaMortalidad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No. Galera", "Fecha de Registro", "Cantidad de Aves muertas", "Cantidad de Aves Seleccionadas"
            }
        ));
        TablaMortalidad.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TablaMortalidadAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane8.setViewportView(TablaMortalidad);

        jScrollPane7.setViewportView(jScrollPane8);

        jScrollPane9.setViewportView(jTextPane3);

        RegistrarNuevasModalidades.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        RegistrarNuevasModalidades.setText("Registrar Nuevas Mortalidades");
        RegistrarNuevasModalidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarNuevasModalidadesActionPerformed(evt);
            }
        });

        ModificarDatosMortalidades.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        ModificarDatosMortalidades.setText("Modificar Datos de Mortalidades");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 915, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RegistrarNuevasModalidades)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ModificarDatosMortalidades)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistrarNuevasModalidades)
                    .addComponent(ModificarDatosMortalidades))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Mortalidad", jPanel4);

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 22)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Datos de Procesos de Engorde");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 963, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarNuevoPesajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarNuevoPesajeActionPerformed
        Pesaje abrir = new Pesaje();
        abrir.setVisible(true);
    }//GEN-LAST:event_RegistrarNuevoPesajeActionPerformed

    private void RegistrarNuevoIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarNuevoIngresoActionPerformed
        Ingreso abrir = new Ingreso();
        abrir.setVisible(true);
    }//GEN-LAST:event_RegistrarNuevoIngresoActionPerformed

    private void RegistrarNuevasModalidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarNuevasModalidadesActionPerformed
        Mortalidad abrir = new Mortalidad();
        abrir.setVisible(true);
    }//GEN-LAST:event_RegistrarNuevasModalidadesActionPerformed

    private void TablaPesajeAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TablaPesajeAncestorAdded
        DefaultTableModel model=(DefaultTableModel) TablaPesaje.getModel();
        String driver = "com.mysql.jdbc.Driver";
        String connection = "jdbc:mysql://localhost:3306/Cargill";
        String user = "root";
        String password = "admi";
        try {
            Class.forName(driver);
            Connection con = DriverManager.getConnection(connection, user, password);
            if (!con.isClosed()) {    
                
                PreparedStatement pesaje = con.prepareStatement("select * from ingresos ");
                ResultSet datospesaje = pesaje.executeQuery();
                while( datospesaje.next()) {
                    int idGaleraSQL = datospesaje.getInt("Galera_idGalera");
                PreparedStatement galera = con.prepareStatement("select * from galera WHERE idGalera = ?");
                galera.setInt(1, idGaleraSQL);
                ResultSet numeroGalera = galera.executeQuery(); 
                while( numeroGalera.next()) {
                    model.addRow(new Object[]{numeroGalera.getString("Numero de Galera"), datospesaje.getString("idGalera"), datospesaje.getString("Numero de Galera"),datospesaje.getString("Nombre Granja")});
                }
                numeroGalera.close();
                galera.close();
                }
                datospesaje.close();
                pesaje.close();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error",e.getMessage(), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_TablaPesajeAncestorAdded

    private void TablaMortalidadAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TablaMortalidadAncestorAdded
        DefaultTableModel model=(DefaultTableModel) TablaGaleras.getModel();
        String driver = "com.mysql.jdbc.Driver";
        String connection = "jdbc:mysql://localhost:3306/Cargill";
        String user = "root";
        String password = "admi";
        try {
            Class.forName(driver);
            Connection con = DriverManager.getConnection(connection, user, password);
            if (!con.isClosed()) {
                PreparedStatement galeras = con.prepareStatement("select * from galera ");
                ResultSet datosgaleras = galeras.executeQuery();
                while( datosgaleras.next() ) {
                    model.addRow(new Object[]{datosgaleras.getString("idGalera"), datosgaleras.getString("Numero de Galera"),datosgaleras.getString("Nombre Granja"),datosgaleras.getString("Zona"),datosgaleras.getInt("Capacidad"),datosgaleras.getString("Supervisor"),datosgaleras.getString("Carrusel"),datosgaleras.getString("ActivacionGalera")});
                }
                datosgaleras.close();
                galeras.close();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error",e.getMessage(), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_TablaMortalidadAncestorAdded

    private void TablaIngresoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TablaIngresoAncestorAdded
        DefaultTableModel model=(DefaultTableModel) TablaIngreso.getModel();
        String driver = "com.mysql.jdbc.Driver";
        String connection = "jdbc:mysql://localhost:3306/Cargill";
        String user = "root";
        String password = "admi";
        try {
            Class.forName(driver);
            Connection con = DriverManager.getConnection(connection, user, password);
            if (!con.isClosed()) {    
                
                PreparedStatement ingreso = con.prepareStatement("select * from ingresos ");
                ResultSet datosIngreso = ingreso.executeQuery();
                while( datosIngreso.next()) {
                    int idGaleraSQL = datosIngreso.getInt("Galera_idGalera");
                PreparedStatement galera = con.prepareStatement("select * from galera WHERE idGalera = ?");
                galera.setInt(1, idGaleraSQL);
                ResultSet numeroGalera = galera.executeQuery(); 
                while( numeroGalera.next()) {
                    model.addRow(new Object[]{numeroGalera.getString("Numero de Galera"), datosIngreso.getDate("Fecha de Ingreso"), datosIngreso.getInt("Cantidad de aves"),datosIngreso.getInt("Edad de reproductora"),datosIngreso.getInt("idIngresos")});
                }
                numeroGalera.close();
                galera.close();
                }
                datosIngreso.close();
                ingreso.close();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error",e.getMessage(), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_TablaIngresoAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProcesosEngorde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProcesosEngorde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProcesosEngorde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProcesosEngorde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProcesosEngorde().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ModificarDatosIngreso;
    private javax.swing.JButton ModificarDatosMortalidades;
    private javax.swing.JButton ModificarDatosPesaje;
    private javax.swing.JButton RegistrarNuevasModalidades;
    private javax.swing.JButton RegistrarNuevoIngreso;
    private javax.swing.JButton RegistrarNuevoPesaje;
    private javax.swing.JTable TablaIngreso;
    public static javax.swing.JTable TablaMortalidad;
    public static javax.swing.JTable TablaPesaje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    // End of variables declaration//GEN-END:variables
}
