package VentanaJava;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pzamoram
 */
public class VentanaUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form VentanaUsuarios
     */
    public VentanaUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InsertarUsuario = new javax.swing.JTextField();
        Contraseña = new javax.swing.JLabel();
        Usuario = new javax.swing.JLabel();
        InsertarContraseña = new javax.swing.JPasswordField();
        Bienvenido = new javax.swing.JLabel();
        IngresarSistema = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InsertarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarUsuarioActionPerformed(evt);
            }
        });

        Contraseña.setFont(new java.awt.Font("Calibri Light", 0, 22)); // NOI18N
        Contraseña.setText("Contraseña");

        Usuario.setFont(new java.awt.Font("Calibri Light", 0, 22)); // NOI18N
        Usuario.setText("Usuario");

        Bienvenido.setFont(new java.awt.Font("Cambria", 0, 30)); // NOI18N
        Bienvenido.setText("Bienvenido al Sistema de Planificación de Cosecha de Agricultura de Cargill Pipasa");

        IngresarSistema.setFont(new java.awt.Font("Calibri Light", 0, 22)); // NOI18N
        IngresarSistema.setText("Ingresar");
        IngresarSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarSistemaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Bienvenido))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Contraseña)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Usuario)
                                .addGap(23, 23, 23)))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(IngresarSistema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(InsertarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(InsertarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(Bienvenido)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InsertarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(InsertarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(IngresarSistema))
                    .addComponent(Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertarUsuarioActionPerformed
    
    public void mostrarPantallaPrincipal(int x) {
        PrincipalPlanificacion lol=new PrincipalPlanificacion(x);
        lol.setVisible(true);
        lol.setLocationRelativeTo(null);
    }
    
    private void IngresarSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarSistemaActionPerformed
	int idUsuario=0;
        String a=InsertarContraseña.getText();
        String b="";
	String driver = "com.mysql.jdbc.Driver";
        String connection = "jdbc:mysql://localhost:3306/cargill";
        String user = "root";
        String password = "admi";
        try {
            Class.forName(driver);
            Connection con = DriverManager.getConnection(connection, user, password);
                           
            if (!con.isClosed()&& InsertarUsuario.getText() != null && InsertarContraseña.getText()!= null) {
                
                               
                PreparedStatement usuario = con.prepareStatement("SELECT * FROM `cargill`.`usuario` Where `Nombre de Usuario`=?;");
                usuario.setString(1, InsertarUsuario.getText());
		ResultSet contrasenaguardada = usuario.executeQuery();
                while( contrasenaguardada.next() ) {
                    b=contrasenaguardada.getString("Contraseña");
                    idUsuario=Integer.parseInt(contrasenaguardada.getString("idUsuario"));
                }
                if(a.equals(b)){
                    mostrarPantallaPrincipal(idUsuario);
                    contrasenaguardada.close();
                    usuario.close();
                    con.close();
                    this.dispose();
                }
                if(!a.equals(b)){
                    JOptionPane.showMessageDialog(null, "El usuario o la contraseña son incorrectos. Por favor vuelva a ingresar los datos correctos", "Datos incorrectos", JOptionPane.ERROR_MESSAGE);
                    contrasenaguardada.close();
                    usuario.close();
                    con.close();
                }
            }
            else {
                JOptionPane.showMessageDialog(null,"Por favor ingrese los datos en todos los campos mostrados","Campos obligatorios incompletos",JOptionPane.ERROR_MESSAGE);
                con.close();
            }
                
                
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Los datos ingresados no están en el formato aceptado", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_IngresarSistemaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bienvenido;
    private javax.swing.JLabel Contraseña;
    private javax.swing.JButton IngresarSistema;
    private javax.swing.JPasswordField InsertarContraseña;
    private javax.swing.JTextField InsertarUsuario;
    private javax.swing.JLabel Usuario;
    // End of variables declaration//GEN-END:variables
}
